SmartBinsWebsite/SmartBinsWebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    #url(r'^register/$', view.register, name='register')
    path('', include('app.urls')),
]

SmartBinsWebsite/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [

    #URLs for pages
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login_view'), 
    path('logout/', views.logout_view, name='logout_view'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('bin/<int:id>/', views.bin_page, name='bin_page'),
    path('historical_bin_data/<int:id>/', views.historical_bin_data, name='historical_bin_data'),
    path('about/', views.about, name='about'),
    path('auth/', views.auth_view, name='auth'),
    path('register/', views.create_account, name='create_account'),
    path('bin_management/', views.bin_management, name='bin_management'),
    path('account/', views.account, name='account'),

    #URLs for device functionality
    path('insert_device_data/', views.insert_device_data, name='insert_device_data'),
    path('create_new_bin/', views.create_new_bin, name='create_new_bin'),
    path('get_time/', views.get_time, name='get_time'),   

    #URLs for Bin CRUD functionality
    path('create_bin/', views.create_bin, name='create_bin'),
    path('edit_bin/', views.edit_bin, name='edit_bin'),
    path('delete_bin/', views.delete_bin, name='delete_bin'),

    path('create_campus/', views.create_campus, name='create_campus'),
    path('edit_campus/', views.edit_campus, name='edit_campus'),
    path('delete_campus/', views.delete_campus , name='delete_campus'),

    path('create_bin_type/', views.create_bin_type, name='create_bin_type'),
    path('edit_bin_type/', views.edit_bin_type, name='edit_bin_type'),
    path('delete_bin_type/', views.delete_bin_type , name='delete_bin_type'),

    #URLs for User CRUD functionality
    path('user_management/', views.user_management, name='user_management'),
    path('user/<int:id>/', views.user_admin, name='user_admin'),
    path('delete_user/', views.delete_user, name='delete_user'), 

    #URLs for JSON/AJAX functionality
    path('get_bins/', views.get_bins, name='get_bins'),
    path('get_bin_logs/', views.get_bin_logs, name='get_bin_logs'),
    path('get_bin_logs_date/', views.get_bin_logs_date, name='get_bin_logs_date'),
    path('get_campuses/', views.get_campuses, name='get_campuses'),      
    
    #URLs for CSV functionality
    path('export_csv/', views.export_csv, name='export_csv'),
    path('report_csv/', views.report_csv, name='report_csv'),    

    #URLs for testing
    path('sample_data/', views.generate_sample_data, name='sample_data'),
    path('delete_all_data/', views.delete_all_data, name='delete_all_data'),
    path('bulk_sample_data/', views.generate_bulk_sample_data, name='bulk_sample_data'),
    path('testing/', views.testing),
    path('test_mail/', views.test_mail, name='test_mail'),

]

SmartBinsWebsite/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from app.models import *

class RegistrationForm(UserCreationForm):
    
    first_name = forms.CharField(label='First Name:', widget=forms.TextInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))

    last_name = forms.CharField(label='Last Name:', widget=forms.TextInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))

    email = forms.EmailField(label='Email:', widget=forms.EmailInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))
   
    username = forms.CharField(label='Username:', widget=forms.TextInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))

    password1 = forms.CharField(label='Password:', widget=forms.PasswordInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))

    password2 = forms.CharField(label='Confrim Password:', widget=forms.PasswordInput(
        attrs={'class':'form-control my-1 mr-sm-2'
        }
    ))

    class Meta:

        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'    
        )

    def save(self, commit=True):

        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        
        return user


class PasswordChangeForm1(PasswordChangeForm):

    old_password = forms.CharField(label='Old Password:', widget=forms.PasswordInput(
        attrs={
            'class':'form-control mb-2 mr-sm-2'
        }
    ))

    new_password1 = forms.CharField(label='New Password:', widget=forms.PasswordInput(
        attrs={
            'class':'form-control mb-2 mr-sm-2'
        }
    ))

    new_password2 = forms.CharField(label='Confrim Password:', widget=forms.PasswordInput(
        attrs={
            'class':'form-control mb-2 mr-sm-2'
        }
    ))

SmartBinsWebsite/app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}
{% block Aboutcolour %}style="color: #000"{% endblock %}
{% block Aboutcurrent %}<span class="sr-only" >(current)</span>{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb mb-0">
        <li class="breadcrumb-item active" aria-current="page">About</li>
    </ol>
{% endblock %}

{% block content %}
<div class="justify-content-center p-2">  
    <h1 class="text-center"> Federation University Smart Bins </h1> 
    <hr>
    <div class="rounded p-2 bg-white shadow text-center" style="max-width: 1000px; margin: auto;">
        <img src="{% static 'app/images/feduni1.jpg' %}" alt="Gippsland Campus" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
            
        <p class="text-center mt-2"> The Smart Bins Project is part of the Federation University Green Campus Initiative which seeks to 
            create more efficient and environmentally friendly campuses around Australia.</p>
            <p>
                This project is prototype solution that utilizes I.O.T smart devices to store, monitor and report campus bin data to facility staff through a web application.
            </p>
            <p> </p> 
        <h2 class="text-center" style="font-size:150%;"> Project Team</h2>
            <p class="text-center"> Headed by Federation University, development of this website was done by Bachelor of Information Technology
                students in partnership with the Federation University Student Support and Services team.</p>

        <h2 class="text-center" style="font-size:150%;"> Development</h2>
            <p class="text-center"> A Sprint based iterative approach was used to develop and build this solution </p>
            <p class="text-center"> Please see the sprint timeline below: </p>
            <p style="font-size:300%;"><i class="fas fa-arrow-down"></i></p>

            

    </div>
    <div class="timeline">
        <div class="containerz left">
          <div class="content shadow">
            <h2>Sprint 1</h2>
            <p>We designed the wireframes for a front end web solution to be made in the Django framework, as well as developing an early database model.</p>
            <img src="{% static 'app/images/designs.jpg' %}" alt="designs" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
          </div>
        </div>
        <div class="containerz right">
          <div class="content shadow">
            <h2>Sprint 2</h2>
            <p>We researched the device and put together a wishlist of parts for an I.O.T smart device and made a start on the frontend of the website.
            </p>
            <img src="{% static 'app/images/arduinoDesign.png' %}" alt="designs" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
          </div>
        </div>
        <div class="containerz left">
            <div class="content shadow">
              <h2>Sprint 3</h2>
              <p>We developed the core front end of the web application for browser and mobile views, experimening with fake data and including features such as user authentication, bin CRUD management and admin functionalities for managing bins.</p>
              <img src="{% static 'app/images/oldDashboard.png' %}" alt="bin map" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
            </div>
          </div>
          <div class="containerz right">
            <div class="content shadow">
              <h2>Sprint 4</h2>
              <p>We expanded the scope to incorporate a google maps API to track and report live bin status on an interactive map, as well as Excel CSV downloadable reports and Email reporting functionality.</p>
              <img src="{% static 'app/images/binMap.png' %}" alt="bin map" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
            </div>
          </div>
          <div class="containerz left">
            <div class="content shadow">
              <h2>Sprint 5</h2>
              <p>Last Sprint was spent squashing bugs, last minute tweaks and formatting documentation as well as including some feedback we received from the client. </p>
              <img src="{% static 'app/images/binPage.png' %}" alt="bin map" class="mx-auto d-block rounded shadow" style="max-width: 100%; height: auto;">
            </div>
          </div>
      </div>
      
  </div>
<style>

/* Set a background color */


/* The actual timeline (the vertical ruler) */
.timeline {
position: relative;
max-width: 1200px;
margin: 0 auto;
}

/* The actual timeline (the vertical ruler) */
.timeline::after {
content: '';
position: absolute;
width: 6px;
background-color: white;
top: 0;
bottom: 0;
left: 50%;
margin-left: -3px;
}

/* Container around content */
.containerz {
padding: 10px 40px;
position: relative;
background-color: inherit;
width: 50%;
}

/* The circles on the timeline */
.containerz::after {
content: '';
position: absolute;
width: 25px;
height: 25px;
right: -17px;
background-color: white;
border: 4px solid #FF9F55;
top: 15px;
border-radius: 50%;
z-index: 1;
}

/* Place the container to the left */
.left {
left: 0;
}

/* Place the container to the right */
.right {
left: 50%;
}

/* Add arrows to the left container (pointing right) */
.left::before {
content: " ";
height: 0;
position: absolute;
top: 22px;
width: 0;
z-index: 1;
right: 30px;
border: medium solid white;
border-width: 10px 0 10px 10px;
border-color: transparent transparent transparent white;
}

/* Add arrows to the right container (pointing left) */
.right::before {
content: " ";
height: 0;
position: absolute;
top: 22px;
width: 0;
z-index: 1;
left: 30px;
border: medium solid white;
border-width: 10px 10px 10px 0;
border-color: transparent white transparent transparent;
}

/* Fix the circle for containers on the right side */
.right::after {
left: -16px;
}

/* The actual content */
.content {
padding: 20px 30px;
background-color: white;
position: relative;
border-radius: 6px;
}

/* Media queries - Responsive timeline on screens less than 600px wide */
@media screen and (max-width: 600px) {
/* Place the timelime to the left */
.timeline::after {
left: 31px;
}

/* Full-width containers */
.containerz {
width: 100%;
padding-left: 70px;
padding-right: 25px;
}

/* Make sure that all arrows are pointing leftwards */
.containerz::before {
left: 60px;
border: medium solid white;
border-width: 10px 10px 10px 0;
border-color: transparent white transparent transparent;
}

/* Make sure all circles are at the same spot */
.left::after, .right::after {
left: 15px;
}

/* Make all right containers behave like the left ones */
.right {
left: 0%;
}
}</style>
</div>
{% endblock %}


SmartBinsWebsite/app/templates/app/account.html
{% extends 'app/base.html' %}

{% block Accountcolour %}style="color: #000"{% endblock %}
{% block Accountcurrent %}<span class="sr-only">(current)</span>{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb mb-0">
    <li class="breadcrumb-item active" aria-current="page">Account</li>
</ol>
{% endblock %}

{% block content %}

<style>
    label{
        margin-bottom: 0;
    }
</style>

{% if user.is_authenticated %}
<div class="d-flex justify-content-center pt-2">
    <h1>Account</h1>
    
</div>
<hr>
<div class="d-flex justify-content-center mb-4" style=" height: auto; width: 100%;">
    <div class="card rounded p-2 text-dark bg-light shadow">
        <div class="container-fluid">
            <div class="row">
                <div class="column-sm-3 p-2">
                        <i class="fas fa-user-circle" style="color: #005caa; font-size:100px;"></i>
                </div>
                <div class="column-sm-9 ml-4">
                    <div class="row">
                        <h2><b>{{ user.username|capfirst }}</b></h2>
                    </div>
                    <div class="row">
                        <h4>
                            {% if user.is_staff %}
                            Administrator
                            {% else %} 
                            User                               
                            {% endif %}
                        </h4>
                    </div>
                    <p class="row pb-1">Last Login: {{ user.last_login }}</p>
                </div>
            </div>
            <div class="row" style="border-top: rgba(0,0,0,0.1) solid 2px;">
                <div class="column-sm-6 p-2">
                    <div class="d-flex justify-content-center">
                        <!-- Change form action to update users details-->
                        <form method="post" id="form">{% csrf_token %}
                                

                            <h5 class="justify-content-center">User Information</h5>
                            <div class="custom-control custom-switch pb-3">
                                <input onclick="toggleForm()" type="checkbox" class="custom-control-input" id="switch" value=0>
                                <label class="custom-control-label" for="switch">Edit</label>
                            </div>
                            <div class="input-group input-group-default" style="margin-bottom: 2px">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="firstName">First Name</span>
                                </div>
                                <input type="text" class="form-control" value="{{ user.first_name }}" name="first_name" id ="first_name" readOnly=true>
                            </div>

                            <div class="input-group input-group-default" style="margin-bottom: 2px">
                                <div class="input-group-prepend" >
                                    <span class="input-group-text" id="lastName">Last Name</span>
                                </div>
                                <input type="text" class="form-control" value="{{ user.last_name }}" name="last_name" id ="last_name" readOnly=true>
                            </div>

                            <div class="input-group input-group-default" style="margin-bottom: 2px">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="emailLabel">Email</span>
                                </div>
                                <input type="email" class="form-control" value="{{ user.email }}" name="email" id="email" readOnly=true>
                            </div>
                            
                            <div class="text-center">
                                <button type="submit" class="btn btn-success mt-3" value="save" name="save">Save Changes</button>
                            </div>
                        </form>
                    </div>    
                </div>
                
                <!-- Change Password Form -->
                <div class="column-sm-6 px-4 py-2 justify-content-center align-items-center">
                    <form class="form-group" method="POST">
                        <h5>Change Password</h5>
                        {% csrf_token %}
                        {{ form }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mt-3" value="change" name="change_password">Update Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
            <div class="d-flex justify-content-center">
                {% if form.errors %}
                    {% for error_field, error_message in form.errors.items %}
                        <div style="width: 400px; text-align: center; margin: auto; margin-bottom: 5px;" class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ error_message|striptags }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>   
                        </div>
                    {% endfor %}
                {% endif %}

                {% if messages %}
                    {% for message in messages %}
                        <div style="width: 400px; text-align: center; margin: auto; margin-bottom: 5px;" class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message|striptags }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>   
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    function toggleForm(){
        toggle = document.getElementById("switch");
        change = [document.getElementById("first_name"), document.getElementById("last_name"), document.getElementById("email")];
        
        console.log(change)
        if (document.getElementById("switch").value == 1){
            toggle.value = "0";
            for (i = 0; i< change.length; i++){
                change[i].readOnly = true;                
            };
        }
        else {
            toggle.value = "1";
            for (i = 0; i< change.length; i++){
                 change[i].readOnly = false;                
            };
        }
    }
    
</script>


{% endif %}
{% endblock %}

SmartBinsWebsite/app/templates/app/historicalbindata.html
{% extends 'app/base.html' %}
  
{% block breadcrumb %}

<ol class="breadcrumb mb-0">
    <li class="breadcrumb-item"><a href="/app/dashboard">Dashboard</a></li> 
    <li class="breadcrumb-item"><a href="/app/bin/{{ bin.get_id }}">Bin {{ bin.get_id }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Historical Data</li> 
</ol>

{% endblock %}

{% block content %}

<div width="80%" class="justify-content-center">

  <h1 class="text-center text-black pt-3">Device Logs for Bin {{ bin.get_id }}</h1>
  <hr>

  <div class="d-flex justify-content-center align-items-center p-2">
    <div class="card text-white d-flex align-items-center">
      <div class="d-flex justify-content-center">
        <table class="table table-responsive table-light table-striped mb-0 shadow rounded">
          <thead>
            <tr>
            <th scope="col"></th>
              <th scope="col">Time Stamp</th>
              <th scope="col">Distance</th>
              <th scope="col">Battery Remaining</th>
            </tr>
          </thead>
          <tbody>
            {% for log in all_logs %}
            <tr>
              <th scope="row"></th>
              <td>{{ log.get_log_timestamp }}</td>
              <td>{{ log.get_distance }}cm</td>
              <td>{{ log.get_battery_remaining }}%</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

SmartBinsWebsite/app/templates/app/useradmin.html
{% extends 'app/base.html' %}
{% block Admincolour %}style="color: #000"{% endblock %}
{% block Admincurrent %}<span class="sr-only">(current)</span>{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">Admin</li>
    <li class="breadcrumb-item"><a href="/app/user_management">User Management</a></li>
    <li class="breadcrumb-item active" aria-current="page">Modify User</li>
</ol>
{% endblock %}

{% block content %}

<div>
    <h1 class="text-center text-black pt-3">User Administration</h1>
</div>
<hr>
<div class="d-flex justify-content-center" style=" height: auto; width: 100%; margin-bottom:150px">
    <div class="card rounded d-flex justify-content-center p-4 bg-white shadow" style="width:500px; margin: auto ">
            <div class="container-fluid">
                <div class="row">
                    <div class="column-sm-3 p-2">
                            <i class="fas fa-user-circle" style="color: #005caa; font-size:100px;"></i>
                    </div>
                    <div class="column-sm-9 ml-4">
                        <div class="row">
                            <h2><b>{{ user_instance.username|capfirst }}</b></h2>
                        </div>
                        <div class="row">
                            <h4>
                                {% if user_instance.is_staff %}
                                Administrator
                                {% else %} 
                                User                               
                                {% endif %}
                            </h4>
                        </div>
                        <p class="row pb-1">Last Login: {{ user_instance.last_login }}</p>
                    </div>
                </div>
                <div class="row justify-content-center" style="border-top: rgba(0,0,0,0.1) solid 2px;">
                    <div class="column-sm-6 p-2">
                        <div class="d-flex justify-content-center">
                            <!-- Change form action to update users details-->
                            <form method="post" id="form">{% csrf_token %}
                            
                                <h5 class="justify-content-center">User Information</h5>
                                {% if user_instance == user %}
                                    <p>Please Update Your own<br>details on the account page</p>
                                {% else %}
                                <div class="custom-control custom-switch">
                                    <input onclick="toggleForm()" type="checkbox" class="custom-control-input" id="switch" value=0>
                                    <label class="custom-control-label" for="switch">Edit</label>
                                </div>
                                {% endif %}
                                <div class="input-group input-group-default" style="margin-bottom: 1px">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="firstName">First Name</span>
                                    </div>
                                    <input type="text" class="form-control" value="{{ user_instance.first_name }}" name="first_name" id ="first_name" readOnly=true>
                                </div>

                                <div class="input-group input-group-default" style="margin-bottom: 1px">
                                    <div class="input-group-prepend" >
                                        <span class="input-group-text" id="lastName">Last Name</span>
                                    </div>
                                    <input type="text" class="form-control" value="{{ user_instance.last_name }}" name="last_name" id ="last_name" readOnly=true>
                                </div>

                                <div class="input-group input-group-default" style="margin-bottom: 1px">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="emailLabel">Email</span>
                                    </div>
                                    <input type="email" class="form-control" value="{{ user_instance.email }}" name="email" id="email" readOnly=true>
                                </div>

                                Admin? <input readonly=true id="staff" type="checkbox" name="staff" 
                                {% if user_instance.is_staff %}
                                    checked
                                {% else %}
                                {% endif %}
                                ></br>

                                Active? <input readonly=true id="active" type="checkbox" name="active" 
                                {% if user_instance.is_active %}
                                    checked
                                {% else %}
                                {% endif %}
                                >
                                <input type="text" value="{{ user_instance.id }}" name="id" readOnly=true hidden>   
                                {% if user_instance != user %}
                                {% if not user_instance.is_superuser %}
                                <div class="text-center p-1">
                                    <button  id="button" type="submit" class="btn btn-success" value="save" name="save">Save Changes</button>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete User</button>
                                </div>
                                {% endif %}
                                {% endif %}
                                
                            </form>
                        </div>
                        <hr>
                        <div class="column-sm-6 px-4 py-2 justify-content-center align-items-center">
                            <form class="form-group" method="POST">
                                <h5>Change Password</h5>
                                {% csrf_token %}
                                <input type="text" value="{{ user_instance.id }}" name="id" readOnly=true hidden> 
                                <label for="id_new_password1">New Password:</label><input type="password" name="new_password1" class="form-control mb-2 mr-sm-2" required="" id="id_new_password1">
                                <label for="id_new_password2">Confrim Password:</label><input type="password" name="new_password2" class="form-control mb-2 mr-sm-2" required="" id="id_new_password2">
                                {% if user_instance != user %}
                                {% if not user_instance.is_superuser %}
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-3" value="change" name="change_password">Update Password</button>
                                </div>
                                {% endif %}
                                {% endif %}
                            </form>
                        </div>
                    </div>    
                </div>
            </div>
            <div class="d-flex justify-content-center">
                {% if form.errors %}
                    {% for error_field, error_message in form.errors.items %}
                        <div style="width: 400px; text-align: center; margin: auto; margin-bottom: 5px;" class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ error_message|striptags }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>   
                        </div>
                    {% endfor %}
                {% endif %}

                {% if messages %}
                    {% for message in messages %}
                        <div style="width: 400px; text-align: center; margin: auto; margin-bottom: 5px;" class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message|striptags }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>   
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Delete Confirm Modal -->
<div id="deleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete User</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete User: {{ user_instance.username }}?</p>
                    <form id="delete_form" action="/app/delete_user/" method="POST" style="display:none">
                        {% csrf_token %}
                        <input type="text" value="{{ user_instance.id }}" name="id" readOnly=true hidden>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" name="delete" value="delete" form="delete_form">DELETE</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">CLOSE</button>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        function toggleForm(){
            toggle = document.getElementById("switch");
            change = [document.getElementById("first_name"), document.getElementById("last_name"), document.getElementById("email"), document.getElementById("staff"), document.getElementById("active")];
            
            if (document.getElementById("switch").value == 1){
                toggle.value = "0";
                for (i = 0; i< change.length; i++){
                    change[i].readOnly = true;                
                };
                
            }
            else {
                toggle.value = "1";
                for (i = 0; i< change.length; i++){
                     change[i].readOnly = false;                
                };
               
            }
        }
        
    </script>
    

{% endblock %}